### ISSUE TITLE
User navigation is not interactive in window is small/mobile

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist.18f.gov#301]
@philipashlock reported that the MENU items on the right hand side of the site are not clickable when the screen is resized. I will reach out to Phil to provide screenshots.

**Comment by philipashlock** [comment]
Tested with Firefox 65 on Mac OS. This only seems to be an issue when logged in. It doesn't seem to be a problem from the frontpage when not logged in. You can see that no hover state is triggered on the menu items and when clicking on one it just closes the menu but otherwise doesn't do anything. 

![federalist-menu](https://user-images.githubusercontent.com/183402/55254805-440aa680-522f-11e9-854b-cea890a57378.gif)

**Comment by eddietejeda** [comment]
@davemcorwin can you take a look at this?

**Comment by davemcorwin** [comment]
I observe the same behavior in Chrome.

**Comment by davemcorwin** [comment]
This appears to be an issue with USWDS, I'm seeing if I can fix...

**Comment by davemcorwin** [comment]
Issue moved to [18F/federalist #2198](https://github.com/18F/federalist/issues/2198) via [**ZenHub**](https://www.zenhub.com/)
